services:
  whatsapp-service:
    build: ./whatsappService
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - openai-service

  openai-service:
    build: ./openAIService
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./admin-key.json:/app/admin-key.json:ro
